version: "3"

services:
  # Client
  client:
    image: "ngapp"
    build: "client/."
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./userimages:/src/assets/usr-img
    container_name: client
  # Server
  server:
    image: "exapp"
    build: "server/."
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./userimages:/src/public/images
    container_name: server
  # database
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./database/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pasquale_sup
      MYSQL_PASSWORD: radiohead
      MYSQL_DATABASE: webgrit_superactivation
    container_name: database

# volumes:
#   images:

## commands
# 1) docker-compose build
# 2) docker-compose up

## Delete all containers
# docker rm $(docker ps -a -q)
## Delete all images
# docker rmi $(docker images -q)

##explore docker volumes
# 1) in console type:  docker run --rm -it -v /:/docker alpine:edge sh
# 2) cd /docker/var/lib/docker/volumes
# 3) ls (list of volumes) 

## explore ounted volumes 
# docker inspect -f '{{.Mounts}}' container-name-or-id

# /assets/user-img/logo-201811140851-toyota.png
# /assets/usr-img/logo-201811140851-toyota.png