version: "3"

services:
  # Client
  client:
    image: "ngapp"
    build: "client/."
    ports:
      - "4200:80"
    container_name: client
  # Server
  server:
    image: "exapp"
    build: "server/."
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    container_name: server  
  # MySQL
  db:
    image: mysql:5.7
    restart: always
    volumes: 
      - ./mysql-dump/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pasquale_sup
      MYSQL_PASSWORD: radiohead
      MYSQL_DATABASE: webgrit_superactivation
    container_name: database  

## commands 
# 1) docker-compose build
# 2) docker-compose up

## Delete all containers
# docker rm $(docker ps -a -q)
## Delete all images
# docker rmi $(docker images -q)