module.exports = [
  {
    SC_ID: 9,
    SC_NOME: "GR s.r.l.",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "Via Primo Maggio 5/2",
    SC_EMAIL: "info@grsrl.net",
    SC_TELEFONO: "051 845 111",
    SC_REFERENTE_NOME: "Uff. Ricerca e Sviluppo",
    SC_TEL_REFERENTE: "ricercaesviluppo@grsrl.net",
    SC_CREATOR_ID: 102,
    SC_TS: "2018-05-28 06:39:24",
    SC_DELETED: 0
  },
  {
    SC_ID: 10,
    SC_NOME: "Raniero carrelli elevatori",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "Via Delle Industrie 12",
    SC_EMAIL: "info@raniero-carrelli.com",
    SC_TELEFONO: "0423948542",
    SC_REFERENTE_NOME: "Daniele M.",
    SC_TEL_REFERENTE: "daniele@raniero-carrelli.com",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:39:38",
    SC_DELETED: 0
  },
  {
    SC_ID: 12,
    SC_NOME: "E Van Gent (NL)",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: " ",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 102,
    SC_TS: "2018-05-28 06:39:14",
    SC_DELETED: 0
  },
  {
    SC_ID: 13,
    SC_NOME: "STE Verona",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "",
    SC_EMAIL: "steverona.sas@gmail.com",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "Tiziano",
    SC_TEL_REFERENTE: "steverona.sas@gmail.com",
    SC_CREATOR_ID: 102,
    SC_TS: "2018-05-28 06:40:07",
    SC_DELETED: 0
  },
  {
    SC_ID: 14,
    SC_NOME: "Florian Legno SPA",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "Via Castellana ",
    SC_EMAIL: "officina.officina@florianinc.com",
    SC_TELEFONO: "3478951662",
    SC_REFERENTE_NOME: "Valter",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:39:22",
    SC_DELETED: 0
  },
  {
    SC_ID: 15,
    SC_NOME: "MATL &amp; BULA (CZ)",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:39:29",
    SC_DELETED: 0
  },
  {
    SC_ID: 16,
    SC_NOME: "FLORIAN BERGER GmbH (A)",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:39:03",
    SC_DELETED: 0
  },
  {
    SC_ID: 17,
    SC_NOME: "Adamo Pasqualino",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "Lamezia Terme",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:39:11",
    SC_DELETED: 0
  },
  {
    SC_ID: 18,
    SC_NOME: "Red Diamont Distribution (GB)",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:38:03",
    SC_DELETED: 0
  },
  {
    SC_ID: 19,
    SC_NOME: "STAPLERPROFI (A)",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:39:45",
    SC_DELETED: 0
  },
  {
    SC_ID: 20,
    SC_NOME: "PETZ (A)",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:39:36",
    SC_DELETED: 0
  },
  {
    SC_ID: 21,
    SC_NOME: "HCH Cristian (D)",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:39:26",
    SC_DELETED: 0
  },
  {
    SC_ID: 22,
    SC_NOME: "OM (PL)",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:39:32",
    SC_DELETED: 0
  },
  {
    SC_ID: 23,
    SC_NOME: "Officina del Carrello",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "Udine",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:39:30",
    SC_DELETED: 0
  },
  {
    SC_ID: 24,
    SC_NOME: "S.G. Carrelli",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:39:41",
    SC_DELETED: 0
  },
  {
    SC_ID: 25,
    SC_NOME: "Emhilia Material Handling",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-28 06:39:16",
    SC_DELETED: 0
  },
  {
    SC_ID: 26,
    SC_NOME: "NikeTrans  (HU)",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "",
    SC_EMAIL: "",
    SC_TELEFONO: "",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-05-29 09:48:33",
    SC_DELETED: 0
  },
  {
    SC_ID: 27,
    SC_NOME: "Montorfano e Beretta",
    SC_PIVA: "",
    SC_COD_FISCALE: "",
    SC_INDIRIZZO: "Corso Bergamo, 13, 23900 Lecco LC",
    SC_EMAIL: "",
    SC_TELEFONO: "0341 420522",
    SC_REFERENTE_NOME: "",
    SC_TEL_REFERENTE: "",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-06-06 10:58:45",
    SC_DELETED: 0
  },
  {
    SC_ID: 35,
    SC_NOME: "test",
    SC_PIVA: "reet",
    SC_COD_FISCALE: "rrr",
    SC_INDIRIZZO: "vca dds",
    SC_EMAIL: "p@test.com",
    SC_TELEFONO: "788",
    SC_REFERENTE_NOME: "sdf",
    SC_TEL_REFERENTE: "057882",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-08-31 11:52:00",
    SC_DELETED: 0
  },
  {
    SC_ID: 58,
    SC_NOME: "test",
    SC_PIVA: "456321we",
    SC_COD_FISCALE: "mmiisd",
    SC_INDIRIZZO: "via caso",
    SC_EMAIL: "posd@fds.ce",
    SC_TELEFONO: "25752",
    SC_REFERENTE_NOME: "io",
    SC_TEL_REFERENTE: "9821",
    SC_CREATOR_ID: 83,
    SC_TS: "2018-09-07 06:16:13",
    SC_DELETED: 0
  },
  {
    "SC_ID": 59,
    "SC_NOME": "permo",
    "SC_PIVA": "gatto",
    "SC_COD_FISCALE": "cane",
    "SC_INDIRIZZO": "prova",
    "SC_EMAIL": "p@gmail.com",
    "SC_TELEFONO": "12/2/2026",
    "SC_REFERENTE_NOME": "w",
    "SC_TEL_REFERENTE": "e",
    "SC_CREATOR_ID": 103,
    "SC_TS": "2018-10-23 12:32:26",
    "SC_DELETED": 0
  }
];
